version: "3"
services:

  api.prod.docker:
    container_name: "medcloud-api"
    restart: "always"
    image: medcloud-api
    user: root
    working_dir: /app/medcloud/backend
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/app/
    expose:
      - 3001
    ports:
      - 3001:3001
    env_file:
      - /etc/environment
